# To create the conda environment:
# $ conda env create -f environment.yml
# 
# To update the conda environment:
# $ conda env update -f environment.yml

## filename: environment.yml

## Environment File Definition

name: tfgpu_env # tensorflow-gpu environment
channels:
  - conda-forge
  - default
dependencies:
  - python=3.9
  ## Core Necessities
  - numpy # -c conda-forge, anaconda
  - nltk=3.6.5
  ## Machine Learning
  - cudnn=8.1 # -c conda-forge | version: 8.1.0.77 (linux/windows)
  #           # -c anaconda | version: 7.6.5 (linux/windows)
  - cudatoolkit=11.2 # -c conda-forge | version: 8.1.0.77 (linux/windows)
  #                  # -c anaconda | version: 11.2 (linux/windows)
  ## Installations with pip
  - pip
  - pip:
    - tensorflow==2.5
    - keras==2.7
    - torch==1.10
    - torchvision==0.11.1
    ## Web App Framework
    - flask==2.0.2
